### ISSUE TITLE
pipe gzipped files

### ISSUE THREAD

**Issue by roblanf** [jueliansiow/heteroplasmy#2]
the script should find gzipped files, and pipe them to seqtk for analysis, rather than unzipping them first, like this:

http://blog.liang2.tw/posts/2015/09/seqtk/

Also pipe the final subsampled output from seqtk back to a gzipped file

**Comment by jueliansiow** [comment]
I'm not sure if i am doing something wrong with piping the output. I can't seem to tell terminal to pipe the result to the next command which in this case is "seqtk trimfq unzippedfile"

Come back and revisit later today.

**Comment by jueliansiow** [comment]
Just tried using "seqtk trimfq $(gzcat $fwd_reads)"

edit: This works but takes a fairly long time. Not sure what the best way to optimize. It would be faster to unzip the file using the GUI program and then run the script.

Edit: this failed. Used way too much memory. For now im going to separate the unzip step and just make it unzip the file.

**Comment by jueliansiow** [comment]
Piping gzip files didnt really work. The work around at the moment is to unzip the file and store them and then remove the files after processing.
