### ISSUE TITLE
add a check for paired reads

### ISSUE THREAD

**Issue by roblanf** [jueliansiow/heteroplasmy#4]
we ONLY want paired reads, so if we specify e.g. 1000 reads, we want ONLY paired reads in that sample

**Comment by roblanf** [comment]
note - you'll have to do this before subsampling, which might require you to save intermediate files for now.

**Comment by jueliansiow** [comment]
Seqtk has a function to check for paired reads but to check the pairs the two files have to be merged which seqtk is also able to do. The mergepe file command also take a while to run.

**Comment by jueliansiow** [comment]
Completed. Reads that arent paired are now discarded. Only reads that are paired are kept and used.
